### ISSUE TITLE
Suggestions/Feature Requests from Paul Dirac

### ISSUE THREAD

**Issue by jnrachit** [BetaTurtle/covid19india#13]
1.  The Home page should show an animated D3.js graph as we  see in NYT or ECONOMIST,  like the circular one posted yesterday, so people can see how the transmission happens in realtime and cluster formations. It'll increase the views as well as the overall look of the site.

2. The India map presently doesnt contain any useful data. It should be replaced with the map with districtwise data posted earlier in the group.

3. There should a live chart or trends on the right side which shows the hotspots of the day, that is maximum increase daily.. it should show which states or areas are showing max increase using an interactive graph.... there are lots of D3.js formats.

4. If possible collaborate with news reporters so as it to get more data, they can get live data from the site  while theyll help us in quick verification.

**Comment by sudevschiz** [comment]
1. Cluster map is being worked on.
2. Districtwise data is being collated.
3. State-wse increment is added as a different issue
4. This is not related to the website
