### ISSUE TITLE
Suggestions/Feature Requests from Metanoia

### ISSUE THREAD

**Issue by jnrachit** [BetaTurtle/covid19india#14]
1. Create a day by day comparison with dates vs positive cases with the countries that have/had comparable scenarios, Like Turkey has a very similar trajectory right now.

1(a) Maybe there are time series analysis available for the historic numbers of other countries which we can fetch and normalize to suit for India's perspective.

**Comment by sudevschiz** [comment]
Not within our scope. Please use global trackers.
