### ISSUE TITLE
Suggestions/Feature Requests from Akhil

### ISSUE THREAD

**Issue by jnrachit** [BetaTurtle/covid19india#19]
1. Can you add a option to find out the nearest case for the user location?
2. Flow Charts of Infected Users / Who were diagnosed positive.

**Comment by suryaceg** [comment]
1. Interesting one. Let's see the possibility based in our cluster chart page.

2. What do you mean by Flow chart? The route map? @jnrachit

**Comment by sudevschiz** [comment]
1. Cluster map is being worked on. 
2. I will create a different feature request for the patient flow chart and refer this there.
