### ISSUE TITLE
Add change from previous day numbers on top of each stat

### ISSUE THREAD

**Issue by sudevschiz** [BetaTurtle/covid19india#3]
![image](https://user-images.githubusercontent.com/4298868/76761357-a2c78800-67d2-11ea-81d2-17015bd3ca79.png)

Similar to this, add the difference from the previous day.

Will need to add a separate column in Cases_Time_Series table.

**Comment by triedcatched** [comment]
This part is already added in the css. Just need to embed a div with class="diff"

```
<div id="kpi-active" data-tippy-content="Tooltip">
      <div class="diff">( +7 )</div>
      <div class="value">665</div>
      <div class="label">Active</div>
    </div>
```


Once we have this data in the spreadsheet, we can enable this

**Comment by sudevschiz** [comment]
Added the delta numbers that need to be shown, in the "Spread Trend" sheet. I feel that's the logical place for it to reside.
Let me know if it should move it the "Statewise" sheet to avoid performance degradation

@triedcatched

**Comment by sudevschiz** [comment]
This is done.
