### ISSUE TITLE
Add daily active case graph

### ISSUE THREAD

**Issue by suryaceg** [BetaTurtle/covid19india#7]
Please remove the +1 number from the top star bar and add a graph showing the daily infection trend.

This can be a simple addition on top of the current graph. This curve can have a different style than the current curves, so people won't confuse it with the other 3 values.

![IMG_20200317_133650_205](https://user-images.githubusercontent.com/840117/76835237-a6035800-6854-11ea-8add-a1082c6ff966.jpg)

**Comment by sudevschiz** [comment]
I have two points to note : 
1. What's the right location for this in the website? I vote against making it longer. We can make it into a carousel to swipe left and right.

<img width="200" alt="Screen Shot 2020-03-17 at 18 24 47" src="https://user-images.githubusercontent.com/4298868/76841879-be876880-687c-11ea-817b-9c6c34fcadd5.png">
2. The y-axis should be better managed. Right now the graph looks like there are huge peaks. I think the y-axis max should be 50 or 100.

**Comment by sudevschiz** [comment]
This has been implemented as a graph below the existing one. 
However keeping the Delta numbers from the previous day so that people can see it on the first view itself.
